### ISSUE TITLE
Add bios to project

### ISSUE THREAD

**Issue by hubyeti** [sammyujan/github-for-developers-7#3]
We should all create great bios in this project. Make sure your bio includes:

```
     - [ ] Your name
     - [ ] Where you are from
     - [ ] A favorite food
     - [ ] A hobby
```

**Comment by sammyujan** [comment]
Created BIO.md file with commit: f7ec424

**Comment by sammyujan** [comment]
Found correct instructions - creating issue in relavance to this

**Comment by sammyujan** [comment]
Created issue - https://github.com/sammyujan/github-for-developers-7/issues/6
